name: 自动同步 DeepSeek 镜像到阿里云
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-image:  # 修改这里，用英文或下划线/连字符
    runs-on: ubuntu-latest
    steps:
      - name: 从 Docker Hub 拉取镜像
        run: docker pull deepseek-ai/deepseek:v1.0.0

      - name: 登录阿里云 Registry
        run: |
          docker login \
            --username=17741189510 \
            --password=${{ secrets.ALIYUN_PASSWORD }} \
            crrpi-96lzszx5lwifh8h.cn-qingdao.personal.cr.aliyuncs.com

      - name: 推送镜像到阿里云
        run: |
          docker tag deepseek-ai/deepseek:v1.0.0 \
            crrpi-96lzszx5lwifh8h.cn-qingdao.personal.cr.aliyuncs.com/deepseek1/deepseek:v1.0.0
          docker push crrpi-96lzszx5lwifh8h.cn-qingdao.personal.cr.aliyuncs.com/deepseek1/deepseek:v1.0.0
